name: Spell Checker

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        pip install pyspellchecker

    - name: Identify changed Python files
      id: changed-files
      run: |
        run git diff --name-only -r HEAD^1 HEAD | xargs

    - name: Run Spell Checker
      run: |
        python spellcheckerTest.py $FILES $(git diff --name-only -r HEAD^1 HEAD | xargs)
