name: Spell Checker

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        pip install pyspellchecker

    - name: Identify changed Python files
      id: changed-files
      run: |
        FILES=$(git diff --name-only origin/main HEAD -- '*.py')
        echo "Files detected: $FILES"
        echo "FILES=$FILES" >> $GITHUB_ENV

    - name: Print files to be checked
      run: |
        echo "Files to be checked: $FILES"

    - name: Run Spell Checker
      run: |
        python pr_spell_checker.py $FILES
