name: Spell Checker

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        pip install pyspellchecker

    - name: Run Spell Checker
      run: |
        python spellcheckerTest.py $(git diff --name-only origin/main HEAD | grep '.py$')
