name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Fetch base branch
        run: git fetch origin main

      - name: Check current branch
        run: git branch

      - name: Run diff check
        run: git diff --name-only origin/main...HEAD

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Print Python version and paths
        run: |
          python --version
          python -c "import sys; print(sys.path)"

      - name: Install pyspellchecker
        run: |
          pip install pyspellchecker
          pip list

      - name: Run spelling check
        run: python github_actions.py
